/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // publicPath: "/build/",
  // serverBuildPath: "build/index.js",
  serverDependenciesToBundle: [
    "recharts",
    "d3-shape",
    "d3-scale",
    "d3-path",
    "d3-array",
    "d3-time",
    "d3-format",
    "d3-interpolate",
    "d3-time-format",
    "d3-color",
    "internmap",
    "@nivo/annotations",
    "@nivo/axes",
    "@nivo/bar",
    "@nivo/colors",
    "@nivo/core",
    "@nivo/legends",
    "@nivo/recompose",
    "@nivo/scales",
    "@nivo/tooltip",
    "@react-spring/animated",
    "@react-spring/core",
    "@react-spring/shared",
    "@react-spring/web",
    "d3-array",
    "d3-collection",
    "d3-color",
    "d3-format",
    "d3-interpolate",
    "d3-path",
    "d3-scale",
    "d3-scale-chromatic",
    "d3-shape",
    "d3-time",
    "d3-time-format",
    "react-lifecycles-compat",
  ],
};
